Master/JobPortalApplication/JobPortalApplication/Models/Application.cs
using System;
using System.Collections.Generic;

namespace JobPortalApplication.Models;

public partial class Application
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public Guid? JobId { get; set; }
	public Guid? CompanyId { get; set; }
	public DateTime? AppliedDate { get; set; }

    public string? Status { get; set; }

    public virtual Job? Job { get; set; }

    public virtual User? User { get; set; }
	 public virtual Company? Company { get; set; }
}

Master/JobPortalApplication/JobPortalApplication/Models/Interview.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JobPortalApplication.Models;

public partial class Interview
{
    public Guid Id { get; set; }
    [ForeignKey(nameof(Company))]
	public Guid? CompanyId { get; set; }

  
	public Guid? JobId { get; set; }

    public Guid? JobseekerId { get; set; }

    public DateTime? Date { get; set; }

    public TimeSpan? Time { get; set; }

    public string? Location { get; set; }

    public string? Status { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual User? CreatedByNavigation { get; set; }

    public virtual Job? Job { get; set; }

	public virtual Company? Company { get; set; }

  public virtual User? Jobseeker { get; set; }
} 

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/AddCompanyMember.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HireMeNow_JobSeekerApp.Pages.JobProvider
{
    public class AddCompanyMemberModel : PageModel
    {

        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;

        public AddCompanyMemberModel(ICompanyService companyService, IMapper mapper)
        {
            _companyService = companyService;
            _mapper = mapper;
        }
        [BindProperty]
		public UserDto Input { get; set; }
        public Guid UserId;
		public void OnGet()
        {
        }
        public void OnPost() {
            //Input.Role=Enums.Roles.CompanyMember;
            //Input.companyId=1;
            //publicService.Register(Input);
            var user = _mapper.Map<User>(Input);
            _companyService.memberRegister(user);
            RedirectToPage("jobprovider/listCompanyMembers");
        }
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/Application.cshtml.cs
using AutoMapper;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
    public class ApplicationModel : PageModel
    {private readonly IUserService userService;
        private readonly IJobService jobService;
        private readonly IApplicationService applicationService;
        private readonly IMapper _mapper;
        public ApplicationModel(IUserService _userService, IMapper mapper, IJobService _jobService, IApplicationService _applicationService)
        {

			userService = _userService;
			_mapper = mapper;
			jobService = _jobService;
			applicationService = _applicationService;
		}

		[BindProperty]

		public List<Application> Applications { get; set; } = new List<Application>();
		public User users { get; set; }
       
		public void OnGet()
        {
			string CompanyId = HttpContext.Session.GetString("CompanyId");
		
			Guid Companyid = new Guid(CompanyId);

			Applications = applicationService.GetAllApplication(Companyid);
            Applications.ForEach((e) =>
            {   
                e.Job = jobService.getJobById(e.JobId.Value);
               
            });

            users = userService.getById(Companyid);
        }
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/ConfirmDelete.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
    public class ConfirmDeleteModel : PageModel
    {

        private readonly IUserService _userService;
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;

        public ConfirmDeleteModel(IUserService userService, ICompanyService companyService, IMapper mapper)
        {
            _userService = userService;
            _companyService = companyService;
            _mapper = mapper;
        }
        [BindProperty]
       public  UserDto member { get; set; }
        public Guid companyId = new Guid("d1b10b2d-13c8-4aff-bb4a-e7b1d779c497");
        [BindProperty(SupportsGet = true)]
        public string userId { get; set; }
        //PublicService publicService = new PublicService();
        public void OnGet(string id)
        {
            userId= id;
            //users=publicService.getCompanyMembers();
            if (id != null)
            {
                var member1 = _userService.getById(Guid.Parse(id));
                member = _mapper.Map<UserDto>(member1);
            }
            //var companyMembers = _userService.memberListing(companyId);
            //string id4 = Request.Form["parameter"];



        }

     
            public IActionResult OnPostButtonClick()
        {
            _companyService.memberDeleteById(new Guid(userId));
            return  RedirectToPage("/jobprovider/listcompanymembers");
        }
       
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/DeleteCompanyMember.cshtml.cs
using AutoMapper;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
    public class DeleteCompanyMemberModel : PageModel
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;

        public DeleteCompanyMemberModel(ICompanyService companyService, IMapper mapper)
        {
            _companyService = companyService;
            _mapper = mapper;
        }
        public void OnGet()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            TempData["UserId"] = userId;

        }
        public IActionResult OnPostButtonClick()
        {
            //Input.Role=Enums.Roles.CompanyMember;
            //Input.companyId=1;
            //publicService.Register(Input);
            //_companyService.memberDeleteById(id);
            return RedirectToPage("jobprovider/listCompanyMembers");
        }
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/Interview.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
	public class InterviewModel : PageModel
	{
		private readonly IInterviewServices _interviewService;
		private readonly IMapper _mapper;
		private readonly IApplicationService _applicationService;
		private IJobService jobService;
		public InterviewModel(IInterviewServices interviewService, IMapper mapper, IApplicationService applicationService, IJobService _jobService)
		{
			_interviewService = interviewService;
			_applicationService = applicationService;
			_mapper = mapper;
			jobService = _jobService;
		}
		[BindProperty]
		public InterviewDto Input { get; set; }
		public string ReturnUrl { get; set; }
		public Interview interview { get; set; } = new();
		public IActionResult OnGet(Guid id)
		{
			interview = _interviewService.GetInterviewById(id);

			interview.Job = jobService.getJobById(interview.JobId.Value);
			if (interview == null)
			{
				return NotFound();
			}

			return Page();


		}

		public IActionResult OnPostRemoveJob(Guid id)
		{
			
			_interviewService.DeleteItemById(id);
			return Page();
		}
	}
	}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/InterviewShedule.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using JobPortalApplication.Repositories;
using JobPortalApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
    public class InterviewSheduleModel : PageModel
    {
		private readonly IInterviewServices _interviewService;
		private readonly IMapper _mapper;
			private readonly IApplicationService _applicationService;
		private IJobService jobService;
		public InterviewSheduleModel(IInterviewServices interviewService, IMapper mapper, IApplicationService applicationService, IJobService _jobService)
        {
			_interviewService = interviewService;
				_applicationService  = applicationService;
			_mapper = mapper;
			jobService = _jobService;
		}
		[BindProperty]
		public InterviewDto Input { get; set; } 
		public string ReturnUrl { get; set; }

		//public void OnGet(string returnUrl = null)
		//{
		//	ReturnUrl = returnUrl;

		//}
		public Application Application { get; set; } = new();

		public IActionResult OnGet(Guid id)
		{
			Application = _applicationService.GetApplicationById(id);
			Application.Job= jobService.getJobById(Application.JobId.Value);

			if (Application == null)
			{
				return NotFound();
			}

			return Page();

		}
		[ValidateAntiForgeryToken]
		public IActionResult OnPost(Guid id)
		{

			Application = _applicationService.GetApplicationById(id);
			Input.JobId = Application.JobId.Value;
			Input.JobseekerId = Application.UserId;
			
			var interview = _mapper.Map<Interview>(Input);
			interview.Id = new Guid();
			
			//interview.JobId=Application.JobId.Value;
			_interviewService.sheduleinterview(interview);

			//var returnUrl =  Url.Content("~/jobprovider/SheduledInterView");
			return RedirectToPage("SheduledInterview");

		}
	}
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/JobList.cshtml.cs
using AutoMapper;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using JobPortalApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
    public class JobListModel : PageModel {
		private readonly IUserService userService;
		private readonly IJobService jobService;
		private readonly IMapper _mapper;

        public JobListModel(IUserService userService, IMapper mapper, IJobService _jobService)
        {
			userService = userService;
			_mapper = mapper;
			jobService = _jobService;
		}
        [BindProperty]

		public List<Job> jobs { get; set; } = new List<Job>();
		public void OnGet()
		{

			var userId = HttpContext.Session.GetInt32("UserId");
			TempData["UserId"] = userId;
			jobs = jobService.GetJobs();

		}
		
			public IActionResult OnPostRemoveJob(Guid id)
			{
			//jobs = jobService.GetJobs();

				////var jobToRemove = jobs.FirstOrDefault(job => job.Id == id);
				////if (jobToRemove != null)
				////{
				jobService.DeleteItemById(id);	
				return Page();
			}
		
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/PostJob.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using JobPortalApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JobPortalApplication.Pages.JobProvider
{
	public class PostJobModel : PageModel
	{
		private readonly IJobService jobService;
		private readonly IMapper _mapper;	 

		public PostJobModel(IMapper mapper, IJobService _jobService)
		{
			jobService = _jobService;
			_mapper = mapper;
		}
		[BindProperty]
		public JobDto Input { get; set; }
		public string ReturnUrl { get; set; }
		public object companyId { get; set; }
		public void OnGet(string returnUrl = null)
		{
			ReturnUrl = returnUrl;
			 companyId = TempData["CompanyId"];
			TempData.Keep();
		}
		public async Task<IActionResult> OnPost(string returnUrl = null)
		{
			returnUrl = returnUrl ?? Url.Content("Public/JobList");
			companyId = TempData["CompanyId"];
			TempData.Keep();
			if (ModelState.IsValid)
			{
				//var CompanyId = HttpContext.Session.GetInt32("UserId");
				Input.CompanyId = new Guid(companyId.ToString());
				var res = jobService.PostJob(_mapper.Map<Job>(Input));
			

				if (res != null)
				{
					TempData["SuccessMessage"] = "Job posted successfully.";

					return RedirectToAction(returnUrl);
				}
				else
				{
					ModelState.AddModelError(string.Empty, "JobPost failed..");
					return Page();
				}

			}
			return Page();
		}

		
	}
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/SheduledInterview.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using JobPortalApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.Design;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace JobPortalApplication.Pages.JobProvider
{
    public class SheduledInterviewModel : PageModel
    {
		private readonly IInterviewServices _interviewService;
		private readonly IMapper _mapper;
		private readonly IUserService _userService;

		public SheduledInterviewModel(IInterviewServices interviewService, IMapper mapper, IUserService userService)
		{

			_interviewService = interviewService;
			_mapper = mapper;
			_userService = userService;
		}
		[BindProperty]
		public List<Interview> Interviews { get; set; }
		public void OnGet()

		{
			String companyId = HttpContext.Session.GetString("CompanyId");

			Guid companid = new Guid(companyId);
			//var interview = _interviewService.GetAll(companid);
			var interview = _interviewService.GetAll(companid);

			Interviews = _mapper.Map<List<Interview>>(interview);
			////var userId = HttpContext.Session.GetInt32("UserId");
			////TempData["UserId"] = userId;
			
		}
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/listCompanyMembers.cshtml.cs
using AutoMapper;
using JobPortalApplication.Dtos;
using JobPortalApplication.Interfaces;
using JobPortalApplication.Models;
using JobPortalApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.Design;

namespace HireMeNow_JobSeekerApp.Pages.JobProvider
{
    public class listCompanyMembersModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;

        public listCompanyMembersModel(IUserService userService,ICompanyService companyService, IMapper mapper)
        {
            _userService = userService;
            _companyService = companyService;
            _mapper = mapper;
        }

        [BindProperty]
        public List<UserDto> users { get; set; } = new();
        public Guid companyId=new Guid("d1b10b2d-13c8-4aff-bb4a-e7b1d779c497");
        //PublicService publicService = new PublicService();
        public void OnGet()
        {
            //users=publicService.getCompanyMembers();
            var companyMembers = _userService.memberListing(companyId);

            users = _mapper.Map<List<UserDto>>(companyMembers);
        }
    }
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/Application.cshtml
@page
@model JobPortalApplication.Pages.JobProvider.ApplicationModel
@{  
    Layout ="_JobProviderLayout";
}

<link href="~/publicassets/css/home.css" rel="stylesheet" />
<style>
    .jobData{
        /*width: 80%;*/
    }

    .btn-apply {
        width: -webkit-fill-available;
        height: 40px;
    }

    .job-card {
        /*width: 60%;*/
        margin:  auto;
        margin-bottom: 13px;
        padding: 10px;
        box-shadow: 3px 4px 17px 0px #504d4d7d;
    }

       /* .job-card :hover {
       
        box-shadow: 3px 4px 17px 0px #504d4d7d;
    }*/
    .applySection{
        display: flex;
        align-content: center;
        flex-direction: column;
        justify-content: center;
    }

    .logoDiv{
        display: flex;
        align-content: center;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .jobListDiv{
        justify-content: center;
    }

    progress {
        width: 100%;
        height: 8px;
        background-color: #ddd;
        border: none;
        border-radius: 5px;
        margin-top:5px;
    }

        progress::-webkit-progress-bar {
            background-color: #ddd;
            border-radius: 5px;
        }

        progress::-webkit-progress-value {
            background-color: #4CAF50;
            border-radius: 5px;
        }

    .JobWrapper {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        align-items: center;
    }

    .tags{
        flex-wrap: wrap
    }

    .progressSpan{
        font-size: small;
    }
   
</style>
<div>
    <h1 align="center">
        <font size="6" face="system-ui" color="black" align="center">
            <b>Find your </b>
        </font>
        <font size="6" face="system-ui" color="#20a6fc" align="center">
            <b>dream job </b>
        </font>
    </h1>
    <p align="center">
        <font face="arial">Find your next career at companies like HubSpot, Nike, and Dropbox</font>
    </p>
    <h2 align="center" color="#3487bf">All Jobs</h2>
    <div class="row jobListDiv" >

        <div class="left col-md-8 scroll">
            @foreach (var app in Model.Applications)
            {
                <div class="job-card" style="">
                <div width="" class="JobWrapper">
                        <div align="center" class="col-md-2 logoDiv">
                          
                            <img src="~/publicassets/images/google symbol.png" width="50px" alt="Google" title="Google" height="50px">
                    </div>
                    <div class="col-md-8 jobData">
                        <b >
                            <font size="5px" color="#3487bf">@app.Job.Title </font>
                        </b>
                        <br>
                       
                        <div>
                          company: <b>@app.Job.Company</b> <br>
                           Location: <b>@app.Job.Location</b> <br>
                        

                        </div>
                        <br>
                        <div class="">

                            <div class="row tags">
                                <div class="fulltime"> Full Time </div>
                                <div class="marketing"> <b>Marketing</b> </div>
                                <div class="design"> Designing </div>
                            </div>  

                        </div>
                        <br>

                    </div>
              @*      <div class="col-md-2 applySection">
                            <form method="post">
                               
                                @{
                                    if (TempData["UserId"] == null)
                                    {
                                        TempData["Id"] = job.Id;
                                       
                                        <input type="hidden" name="parameter" value="@job.Id" />
                                        <input type="submit" class="btn btn-outline-primary btn-apply" value="Apply" asp-page-handler="ButtonClick" >
                                    }
                                    else{
                                        
                                        <input type="hidden" name="parameter" value="@job.Id" />
                                        <input type="submit" class="btn btn-outline-primary btn-apply" value="Apply" asp-page-handler="ButtonClick" >
                                    }

                            }
                        </form>
                      

                            <progress id="progressBar" value=@job.AppliedCount max=@job.VacanciesCount></progress>
                            <span class="progressSpan">@job.AppliedCount applied of @job.VacanciesCount capacity</span>
                    </div>*@
                 <div class="col-md-2 applySection">
                            <form method="post">
                               
                                @{
                                    if (TempData["CompanyId"] == null)
                                    {
                                        TempData["Id"] = app.Id;
                                       
                                        <input type="hidden" name="parameter" value="@app.Id" />
                                        <input type="submit" class="btn btn-outline-primary btn-apply" value="Shedule" asp-page-handler="ButtonClick" >
                                    }
                                    else{
                                        
                                        <input type="hidden" name="parameter" value="@app.Id" />
                                        //<input type="submit" class="btn btn-outline-primary btn-apply" value="Shedule" asp-route-applicationId="@app.Id asp-page-handler="ButtonClick" >
                                                    <a asp-page="InterviewShedule"  class="btn btn-outline-primary btn-apply" asp-route-id="@app.Id">Schedule Interview</a>
        

                                    }

                            }
                        </form>
                      
                </div>

                    </div>
                </div>
               
            }
           
            <div class="center">

                <div class="pagination">
                    <a href="#">&laquo;</a>
                    <a href="#" ="active">1</a>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <a href="#">4</a>
                    <a href="#">5</a>
                    <a href="#">6</a>
                    <a href="#">&raquo;</a>
                </div>
            </div>
            
        </div>



   

</div>
class

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/ConfirmDelete.cshtml
@page
@model JobPortalApplication.Pages.JobProvider.ConfirmDeleteModel
@{
    Layout = "_JobProviderLayout";
}
<h2>CONFIRM DELETE</h2>



<div class="card" style="width: 18rem;">
  <div class="card-body">

    @*<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
*@



        <b> @Model.member.Email </b><br>
        <form method="post">
         <input type="button" value="Confirm Delete" class="btn btn-danger" >

        <input type="hidden" name="memberId" value="@Model.member.Id">
            <input asp-for="userId" type="hidden" class="form-control" placeholder="Enter FirstName" id="fname" size="30" required="">

        <input type="submit" value="delete" class="btn btn-danger" asp-page-handler="ButtonClick">

        </form>

  </div>
</div>

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/DeleteCompanyMember.cshtml
@page
@model JobPortalApplication.Pages.JobProvider.DeleteCompanyMemberModel
@{
}

Master/JobPortalApplication/JobPortalApplication/Pages/JobProvider/Interview.cshtml
@page
@model JobPortalApplication.Pages.JobProvider.InterviewModel
@{
    Layout = "_InterviewLayout" ;
}
@Html.AntiForgeryToken()
<body>
	<div class="container-fluid">
		<div  class="row">
			<div class="col-md-2 text-nowrap bg-primary">
				<nav class="navbar  navbar-expand-md sidebar navbar-dark">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	  					<span class="navbar-toggler-icon bg-dark"></span>
	  				</button>
	 				<div class="collapse  navbar-collapse sidebar " id="collapsibleNavbar">
	 					<ul class="list-group text-white list-unstyled">
	 						<li class="list-group-item border-0 bg-primary pt-5 pb-5 ">
	 							<h4 class="h4-fluid">HireMe Now</h4>
	 						</li>
	 						
	 						<li class="list-group-item border-0 bg-primary">
	 							<p><img src="~/asset/images/dashboard 1 (2).png" >  Dash Board</p>
	 						</li>
	 						<li class="list-group-item border-0 bg-primary">
	 							<p><img src="~/asset/images/suitcase 2 (1).png" >  Jobs</p>
	 						</li>
			    			<li class="list-group-item border-0 bg-primary">
	 							<p><img src="~/asset/images/application (1) 1 (2).png">  Applications</p>
	 						</li>
			   				<li class="list-group-item border-0 bg-primary">
	 							<p><a class="nav-link text-white" asp-area="" asp-page="/SheduledInterview"><img src="~/images/question (1) 1.png"> Interviews</a></p>
	 						</li>
	 						<li class="list-group-item border-0 bg-primary">
	 							<p><img src="~/asset/images/message 1 (2).png" > Messages</p>
	 						</li>
			    
			    			<li class="list-group-item border-0 bg-primary">
	 							<p><img src="~/asset/images/settings 1 (1).png">  Settings</p>
	 						</li>
			    			<li class="list-group-item border-0 bg-primary">
			    				<img class="img-fluid" src="~/asset/images/add-group (1) 1 (2).png"><br>
				        		<span class="text-white">Add New</span>
			    			</li>
	 					</ul>
	 				</div>
 				</nav>
 			</div>
 			<div class="col-md-10">
 				<div class="row">
 					<div class="col-md-11 mt-5  border-bottom pb-4 ">
 						<!-- <img class="img-fluid float-right m-2 pt-4" src="~/asset/images/arrow-down.png"> -->
 						<!-- <span class="float-right pt-3 m-2"><strong>Olivia</strong></span> -->
 						<select class="form-select border-0 float-right  mt-4" aria-label="Default select example">
							<option selected><strong>Olivia</strong></option>
											
							</select>
 						<img class="img-fluid float-right" src="~/asset/images/cheerful-curly-business-girl-wearing-glasses 2.png">
 						<img class="img-fluid float-right pt-2 m-2 " src="~/asset/images/Group 5689.png" width="30" height="30">
 					</div>
 				</div>
 				<div class="row">
 					<div class="col-md-11 shadow-sm">
 						<div class="row">
 							<div class="col-md-11">
 								<h3 class="h3-default text-right mr-5 ">Short List</h3>
 							</div>
 						</div>
                        <div class="row">
 							<div class="col-md-10 mx-auto d-block border-top ">
 								<form method="post"  asp-page-handler="RemoveJob" asp-route-id="@Model.interview.Id" >
									<div class="form-group text-dark">
										<label for="Job Title" ><h4>Job Title</h4></label>
										@*<input asp-for="Input.JobId" type="hidden" value="@Model.Application.JobId">
										<input asp-for="Input.JobseekerId" type="hidden" value="@Model.Application.UserId">*@
										<input asp-for="Input.Post" type="text" name="Post" placeholder="Select Jobtitle" class="form-control bg-light p-4 border-0 rounded " required="" value ="@Model.interview.Job.Title">
                                    </div>
									<div class="form-group text-dark p-1">
										<label for="Date"><h4>Date</h4></label>
										<img class="img-fluid float-right" src="~/asset/images/calendar (4) 1.png">
										<input asp-for="Input.Date" value ="@Model.interview.Date" type="Date" name="date" placeholder="@Model" class="form-control bg-light p-4 border-0 rounded w-75 "required=""  >
									</div>
									<div class="form-group text-dark p-1">
										<label for="Time"><h4>Time</h4></label>
										<img class="img-fluid float-right" src="~/asset/images/clock 1.png">
										<input asp-for="Input.Time" type="Time" name="time" placeholder=" Enter time" class="form-control bg-light p-4 border-0 rounded w-75"required="" value="@Model.interview.Time">
									</div>
									<div class="form-group text-dark p-2">
										<label for="Location"><h4>Location</h4></label>
										<img class="img-fluid float-right" src="~/asset/images/location 1.png">
										<input asp-for="Input.Location" type="text" name="location" value="" placeholder="Enter location" class="form-control bg-light p-4 border-0 rounded mb-5 w-75"required="" value="@Model.interview.Location">
									</div>
									<div class="form-group d-inline ">
									@*	<input type="submit" value="send"/>*@

									 <input class="btn text-white mr-5 bg-primary text-white" type="submit" value="Remove"></input>
									<label ><h5>Push Notification</h5></label>
		 								<img class="img-fluid mr-5" src="~/asset/images/Group 14.png">
		 								<label><h5>Email Notifications</h5></label>
										<img class="img-fluid" src="~/asset/images/Group 14.png">
									</div>
								</form>
 							</div>
 						</div>
 					</div>
 				</div>
 			</div>
 		</div>
 	</div>
</body>